//==============================================================================
//	CAUTION: This file is generated by IBatisNetGen.DaoImpl.cst at 2010-11-29 21:19:41
//				By xincai.wu
//==============================================================================
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using TMM.Model;
using TMM.Persistence;


namespace TMM.Service.Dal.Sys {

	/// <summary>
    /// 名称：SCatalogDao 数据层
    /// 开发者：
    /// 创建时间：2010-11-29 19:03:15
    /// 功能描述：
    /// </summary>
    public partial class S_CatalogDal {

		/// <summary>
        /// 取得记录数
        /// </summary>
        /// <param name="param">可选参数为：</param>
        /// <returns></returns>
		public int GetCount(Hashtable param) {
			if (param == null)
                param = new Hashtable();
				
			String stmtId = "S_Catalog.GetCount";
			return SqlMapper.Instance().QueryForObject<int>(stmtId, null);
		}

		/// <summary>
        /// 提取数据
        /// </summary>
        /// <param name="param">可选参数为：</param>
        /// <param name="orderBy">排序方式:默认为“CatalogId asc”</param>
        /// <param name="first">起始记录：从0开始</param>
        /// <param name="rows">提取的条数</param>
        /// <returns></returns>
		public IList<S_Catalog> GetList(Hashtable param,string orderBy,int? first,int? rows) 
		{
			if (param == null)
                param = new Hashtable();
            if (first.HasValue && rows.HasValue)
            {
                param.Add("Top", first + rows);
                param.Add("StartRecord", first);
            }

            if (string.IsNullOrEmpty(orderBy))
                param.Add("OrderBy", "CatalogId asc");
			else
                param.Add("OrderBy", orderBy);
				
			String stmtId = "S_Catalog.GetList";
			return SqlMapper.Instance().QueryForList<S_Catalog>(stmtId, param);
		}
		
		/// <summary>
        /// 提取数据
        /// </summary>
        /// <param name="catalogId"></param>
        /// <returns></returns>
		public S_Catalog Get(Int32 catalogId) {
			String stmtId = "S_Catalog.Get";
			return SqlMapper.Instance().QueryForObject<S_Catalog>(stmtId, catalogId);
		}

		/// <summary>
        /// 插入数据
        /// </summary>
        /// <param name="obj">对象</param>
        /// <returns>返回：该条数据的主键Id</returns>
		public int Insert(S_Catalog obj) {
			if (obj == null) throw new ArgumentNullException("obj");
			String stmtId = "S_Catalog.Insert";
			return SqlMapper.Instance().QueryForObject<int>(stmtId, obj);
		}
		
		/// <summary>
        /// 更新数据
        /// </summary>
        /// <param name="obj"></param>
        /// <returns>返回：ture 成功，false 失败</returns>
		public bool Update(S_Catalog obj) {
			if (obj == null) throw new ArgumentNullException("obj");
			String stmtId = "S_Catalog.Update";
			int result = SqlMapper.Instance().QueryForObject<int>(stmtId, obj);
			return result > 0 ? true : false;
		}
		
		/// <summary>
        /// 删除数据
        /// </summary>
        /// <param name="catalogId"></param>
        /// <returns>返回：ture 成功，false 失败</returns>
		public bool Delete(Int32 catalogId) {
			String stmtId = "S_Catalog.Delete";
			int result = SqlMapper.Instance().QueryForObject<int>(stmtId, catalogId);
			return result > 0 ? true : false;
		}
		
	}

}
