//==============================================================================
//	CAUTION: This file is generated by IBatisNetGen.Entity.cst at 2010-12-17 22:06:28
//				Any manual editing will be lost in re-generation.
//==============================================================================
using System;
using System.Collections.Generic;
using System.Text;

namespace TMM.Model  {
	
    /// <summary><c>AccountLog</c> Business Object.</summary>
    [Serializable]
    public partial class AccountLog {
        
        #region LogId

        private Int32 m_logId;
		
		/// <summary>Gets or sets LogId</summary>
        public Int32 LogId {
        	get { return m_logId; }
        	set { m_logId = value;}        
        }
		
	    #endregion
		
        #region UserId

        private Int32 m_userId;
		
		/// <summary>Gets or sets UserId</summary>
        public Int32 UserId {
        	get { return m_userId; }
        	set { m_userId = value;}        
        }
		
	    #endregion
		
        #region OrderId

        private Decimal m_orderId;
		
		/// <summary>Gets or sets OrderId</summary>
        public Decimal OrderId {
        	get { return m_orderId; }
        	set { m_orderId = value;}        
        }
		
	    #endregion
		
        #region Amount

        private Decimal m_amount;
		
		/// <summary>Gets or sets Amount</summary>
        public Decimal Amount {
        	get { return m_amount; }
        	set { m_amount = value;}        
        }
		
	    #endregion
		
        #region AccountWay

        private Int32 m_accountWay;

        /// <summary>收支途径类型</summary>
        public Int32 AccountWay {
        	get { return m_accountWay; }
        	set { m_accountWay = value;}        
        }
		
	    #endregion
		
        #region Ip

        private String m_ip;
		
		/// <summary>Gets or sets Ip</summary>
        public String Ip {
        	get { return m_ip; }
        	set { m_ip = value;}        
        }
		
	    #endregion
		
        #region AdminRemark

        private String m_adminRemark;
		
		/// <summary>Gets or sets AdminRemark</summary>
        public String AdminRemark {
        	get { return m_adminRemark; }
        	set { m_adminRemark = value;}        
        }
		
	    #endregion

        public DateTime CreateTime { get; set; }

        /// <summary>
        /// 账户日志所关联的产品
        /// </summary>
        public DDocInfo Doc { get; set; }
        /// <summary>
        /// 支付方式
        /// </summary>
        public int? PayWay { get; set; }
	}
    /// <summary>
    /// 收支途径类型
    /// </summary>
    public enum AmountWay
    {
        /// <summary>
        /// 默认未知
        /// </summary>
        N = 0,
        /// <summary>
        /// 账户充值
        /// </summary>
        In = 10,
        /// <summary>
        /// 成功绑定商务会员卡后充入
        /// </summary>
        CIn = 11,
        /// <summary>
        /// 代用户手动充入
        /// </summary>
        MIn = 12,

        /// <summary>
        /// 账户花销
        /// </summary>
        Out = 20,
        /// <summary>
        /// 客服扣除
        /// </summary>
        AOut = 21,
        /// <summary>
        /// 管理员扣除
        /// </summary>
        MOut = 22,
        /// <summary>
        /// 支付悬赏中标的文档
        /// </summary>
        ROut = 23,
        /// <summary>
        /// 兑换扣除账户余额
        /// </summary>
        EOut = 24,
        /// <summary>
        /// 通过后台退款
        /// </summary>
        AR = 30,
        /// <summary>
        /// 通过后台返现
        /// </summary>
        AF = 35,
        /// <summary>
        /// 通过数据库退款
        /// </summary>
        MR = 40,
        /// <summary>
        /// 通过数据库返现
        /// </summary>
        MF = 45,
        /// <summary>
        /// 订单交易失败退款
        /// </summary>
        OR = 50,
        /// <summary>
        /// 新年抽奖返现
        /// </summary>
        DF = 60,
        /// <summary>
        /// 发表商品评论获奖返现
        /// </summary>
        GMF = 70,
        /// <summary>
        /// 邀请返现
        /// </summary>
        YQF = 80,
        /// <summary>
        /// 收入（出售文档所获得收入）
        /// </summary>
        INCOME = 90,
        /// <summary>
        /// 收入（悬赏文档投稿）
        /// </summary>
        INCOME_TG = 91


    }
	
}
