//==============================================================================
//	CAUTION: This file is generated by IBatisNetGen.Entity.cst at 2010-12-17 22:06:28
//				Any manual editing will be lost in re-generation.
//==============================================================================
using System;
using System.Collections.Generic;
using System.Text;

namespace TMM.Model {
	
    /// <summary><c>ExchangeAccount</c> Business Object.</summary>
    [Serializable]
    public partial class ExchangeAccount {
        
        #region AccountId

        private Int32 m_accountId;
		
		/// <summary>Gets or sets AccountId</summary>
        public Int32 AccountId {
        	get { return m_accountId; }
        	set { m_accountId = value;}        
        }
		
	    #endregion
		
        #region UserId

        private Int32 m_userId;
		
		/// <summary>Gets or sets UserId</summary>
        public Int32 UserId {
        	get { return m_userId; }
        	set { m_userId = value;}        
        }
		
	    #endregion
		
        #region AccountName

        private String m_accountName;
		
		/// <summary>Gets or sets AccountName</summary>
        public String AccountName {
        	get { return m_accountName; }
        	set { m_accountName = value;}        
        }
		
	    #endregion
		
        #region AccountNo

        private String m_accountNo;
		
		/// <summary>Gets or sets AccountNo</summary>
        public String AccountNo {
        	get { return m_accountNo; }
        	set { m_accountNo = value;}        
        }
		
	    #endregion
		
        #region AccountType

        private Int32 m_accountType;
		
		/// <summary>1：支付宝 2：银行账户</summary>
        public Int32 AccountType {
        	get { return m_accountType; }
        	set { m_accountType = value;}        
        }
		
	    #endregion
		
        #region BankName

        private String m_bankName;
		
		/// <summary>Gets or sets BankName</summary>
        public String BankName {
        	get { return m_bankName; }
        	set { m_bankName = value;}        
        }
		
	    #endregion
		
        #region ProvinceId

        private Int32? m_provinceId;
		
		/// <summary>Gets or sets ProvinceId</summary>
        public Int32? ProvinceId {
        	get { return m_provinceId; }
        	set { m_provinceId = value;}        
        }
		
	    #endregion
		
        #region ProvinceName

        private String m_provinceName;
		
		/// <summary>Gets or sets ProvinceName</summary>
        public String ProvinceName {
        	get { return m_provinceName; }
        	set { m_provinceName = value;}        
        }
		
	    #endregion
		
        #region AreaId

        private Int32? m_areaId;
		
		/// <summary>Gets or sets AreaId</summary>
        public Int32? AreaId {
        	get { return m_areaId; }
        	set { m_areaId = value;}        
        }
		
	    #endregion
		
        #region AreaName

        private String m_areaName;
		
		/// <summary>Gets or sets AreaName</summary>
        public String AreaName {
        	get { return m_areaName; }
        	set { m_areaName = value;}        
        }
		
	    #endregion
		
        #region CreateTime

        private DateTime m_createTime;
		
		/// <summary>Gets or sets CreateTime</summary>
        public DateTime CreateTime {
        	get { return m_createTime; }
        	set { m_createTime = value;}        
        }
		
	    #endregion
		

	}
	
}
