//==============================================================================
//	CAUTION: This file is generated by IBatisNetGen.Entity.cst at 2010-12-17 22:06:28
//				Any manual editing will be lost in re-generation.
//==============================================================================
using System;
using System.Collections.Generic;
using System.Text;

namespace TMM.Model
{
	
    /// <summary><c>FileInfo</c> Business Object.</summary>
    [Serializable]
    public partial class FileInfo {
        
        #region Id

        private Int32 m_id;
		
		/// <summary>Gets or sets Id</summary>
        public Int32 Id {
        	get { return m_id; }
        	set { m_id = value;}        
        }
		
	    #endregion
		
        #region FileId

        private Guid m_fileId;
		
		/// <summary>Gets or sets FileId</summary>
        public Guid FileId {
        	get { return m_fileId; }
        	set { m_fileId = value;}        
        }
		
	    #endregion
		
        #region FileName

        private String m_fileName;
		
		/// <summary>Gets or sets FileName</summary>
        public String FileName {
        	get { return m_fileName; }
        	set { m_fileName = value;}        
        }
		
	    #endregion
		
        #region FileLength

        private Int32 m_fileLength;
		
		/// <summary>Gets or sets FileLength</summary>
        public Int32 FileLength {
        	get { return m_fileLength; }
        	set { m_fileLength = value;}        
        }
		
	    #endregion
		
        #region PhysicalPath

        private String m_physicalPath;
		
		/// <summary>Gets or sets PhysicalPath</summary>
        public String PhysicalPath {
        	get { return m_physicalPath; }
        	set { m_physicalPath = value;}        
        }
		
	    #endregion
		
        #region CreateTime

        private DateTime m_createTime;
		
		/// <summary>Gets or sets CreateTime</summary>
        public DateTime CreateTime {
        	get { return m_createTime; }
        	set { m_createTime = value;}        
        }
		
	    #endregion
		

	}
	
}
