//==============================================================================
//	CAUTION: This file is generated by IBatisNetGen.Entity.cst at 2010-12-17 15:46:13
//				Any manual editing will be lost in re-generation.
//==============================================================================
using System;
using System.Collections.Generic;
using System.Text;

namespace TMM.Model
{
	
    /// <summary><c>MCatalog</c> Business Object.</summary>
    [Serializable]
    public partial class MCatalog {
        
        #region CateId

        private Int32 m_cateId;
		
		/// <summary>Gets or sets CateId</summary>
        public Int32 CateId {
        	get { return m_cateId; }
        	set { m_cateId = value;}        
        }
		
	    #endregion
		
        #region UserId

        private Int32 m_userId;
		
		/// <summary>Gets or sets UserId</summary>
        public Int32 UserId {
        	get { return m_userId; }
        	set { m_userId = value;}        
        }
		
	    #endregion
		
        #region CateText

        private String m_cateText;
		
		/// <summary>Gets or sets CateText</summary>
        public String CateText {
        	get { return m_cateText; }
        	set { m_cateText = value;}        
        }
		
	    #endregion
		
        #region CreateTime

        private DateTime m_createTime;
		
		/// <summary>Gets or sets CreateTime</summary>
        public DateTime CreateTime {
        	get { return m_createTime; }
        	set { m_createTime = value;}        
        }
		
	    #endregion
		
        #region CatalogType

        private Int32 m_catalogType;
		
		/// <summary>1:上传文件夹 2：分类文件夹</summary>
        public Int32 CatalogType {
        	get { return m_catalogType; }
        	set { m_catalogType = value;}        
        }
		
	    #endregion
		
        #region DocCount

        private Int32 m_docCount;
		
		/// <summary>Gets or sets DocCount</summary>
        public Int32 DocCount {
        	get { return m_docCount; }
        	set { m_docCount = value;}        
        }
		
	    #endregion
		

	}
	
}
