//==============================================================================
//	CAUTION: This file is generated by IBatisNetGen.Entity.cst at 2010-12-17 15:46:13
//				Any manual editing will be lost in re-generation.
//==============================================================================
using System;
using System.Collections.Generic;
using System.Text;

namespace TMM.Model  
{
	
    /// <summary><c>MFavorite</c> Business Object.</summary>
    [Serializable]
    public partial class MFavorite {
        
        #region FavId

        private Int32 m_favId;
		
		/// <summary>Gets or sets FavId</summary>
        public Int32 FavId {
        	get { return m_favId; }
        	set { m_favId = value;}        
        }
		
	    #endregion
		
        #region UserId

        private Int32 m_userId;
		
		/// <summary>Gets or sets UserId</summary>
        public Int32 UserId {
        	get { return m_userId; }
        	set { m_userId = value;}        
        }
		
	    #endregion
		
        #region DocId

        private Int32 m_docId;
		
		/// <summary>Gets or sets DocId</summary>
        public Int32 DocId {
        	get { return m_docId; }
        	set { m_docId = value;}        
        }
		
	    #endregion
		
        #region CreateTime

        private DateTime m_createTime;
		
		/// <summary>Gets or sets CreateTime</summary>
        public DateTime CreateTime {
        	get { return m_createTime; }
        	set { m_createTime = value;}        
        }
		
	    #endregion
		
        #region FavCateId

        private Int32? m_favCateId;
		
		/// <summary>Gets or sets FavCateId</summary>
        public Int32? FavCateId {
        	get { return m_favCateId; }
        	set { m_favCateId = value;}        
        }
		
	    #endregion
		
        #region FavCatalog

        private String m_favCatalog;
		
		/// <summary>Gets or sets FavCatalog</summary>
        public String FavCatalog {
        	get { return m_favCatalog; }
        	set { m_favCatalog = value;}        
        }
		
	    #endregion

        private string title;
        public string Title {
            get { return title; }
            set { title = value; }
        }

        private U_UserInfo userInfo;
        public U_UserInfo U_UserInfo {
            get { return userInfo; }
            set { userInfo = value; }
        }

        public string DocType { get; set; }

        public string HeadIcon { get; set; }
	}
	
}
