//==============================================================================
//	CAUTION: This file is generated by IBatisNetGen.Entity.cst at 2010-12-17 15:46:13
//				Any manual editing will be lost in re-generation.
//==============================================================================
using System;
using System.Collections.Generic;
using System.Text;

namespace TMM.Model  {
	
    /// <summary><c>MMessage</c> Business Object.</summary>
    [Serializable]
    public partial class M_Message {
        
        #region Mid

        private Int64 m_mid;
		
		/// <summary>Gets or sets Mid</summary>
        public Int64 Mid {
        	get { return m_mid; }
        	set { m_mid = value;}        
        }
		
	    #endregion
		
        #region SenderId

        private Int32? m_senderId;
		
		/// <summary>Gets or sets SenderId</summary>
        public Int32? SenderId {
        	get { return m_senderId; }
        	set { m_senderId = value;}        
        }
		
	    #endregion
		
        #region RecieverId

        private Int32? m_recieverId;
		
		/// <summary>Gets or sets RecieverId</summary>
        public Int32? RecieverId {
        	get { return m_recieverId; }
        	set { m_recieverId = value;}        
        }
		
	    #endregion
		
        #region Title

        private String m_title;
		
		/// <summary>Gets or sets Title</summary>
        public String Title {
        	get { return m_title; }
        	set { m_title = value;}        
        }
		
	    #endregion
		
        #region Content

        private String m_content;
		
		/// <summary>Gets or sets Content</summary>
        public String Content {
        	get { return m_content; }
        	set { m_content = value;}        
        }
		
	    #endregion
		
        #region CreateTime

        private DateTime? m_createTime;
		
		/// <summary>Gets or sets CreateTime</summary>
        public DateTime? CreateTime {
        	get { return m_createTime; }
        	set { m_createTime = value;}        
        }
		
	    #endregion
		
        #region IsRead

        private Boolean m_isRead;
		
		/// <summary>Gets or sets IsRead</summary>
        public Boolean IsRead {
        	get { return m_isRead; }
        	set { m_isRead = value;}        
        }
		
	    #endregion
		
        #region Mtype

        private Int32 m_mtype;
		
		/// <summary>Gets or sets Mtype</summary>
        public Int32 Mtype {
        	get { return m_mtype; }
        	set { m_mtype = value;}        
        }
		
	    #endregion
		
        #region RefId

        private Int32? m_refId;
		
		/// <summary>Gets or sets RefId</summary>
        public Int32? RefId {
        	get { return m_refId; }
        	set { m_refId = value;}        
        }
		
	    #endregion
		
        #region SendDeleteFlag

        private Boolean m_sendDeleteFlag;
		
		/// <summary>Gets or sets SendDeleteFlag</summary>
        public Boolean SendDeleteFlag {
        	get { return m_sendDeleteFlag; }
        	set { m_sendDeleteFlag = value;}        
        }
		
	    #endregion
		
        #region RecieveDeleteFlag

        private Boolean m_recieveDeleteFlag;
		
		/// <summary>Gets or sets RecieveDeleteFlag</summary>
        public Boolean RecieveDeleteFlag {
        	get { return m_recieveDeleteFlag; }
        	set { m_recieveDeleteFlag = value;}        
        }
		
	    #endregion
		

	}
	
}
