//==============================================================================
//	CAUTION: This file is generated by IBatisNetGen.Entity.cst at 2010-12-17 22:06:28
//				Any manual editing will be lost in re-generation.
//==============================================================================
using System;
using System.Collections.Generic;
using System.Text;

namespace TMM.Model  {
	
    /// <summary><c>MAccount</c> Business Object.</summary>
    [Serializable]
    public partial class MAccount {
        
        #region AccountId

        private Int32 m_accountId;
		
		/// <summary>Gets or sets AccountId</summary>
        public Int32 AccountId {
        	get { return m_accountId; }
        	set { m_accountId = value;}        
        }
		
	    #endregion
		
        #region UserId

        private Int32 m_userId;
		
		/// <summary>Gets or sets UserId</summary>
        public Int32 UserId {
        	get { return m_userId; }
        	set { m_userId = value;}        
        }
		
	    #endregion
		
        #region Amount

        private Decimal m_amount;
		
		/// <summary>Gets or sets Amount</summary>
        public Decimal Amount {
        	get { return m_amount; }
        	set { m_amount = value;}        
        }
		
	    #endregion
		
        #region UserLevel

        private Int32 m_userLevel;
		
		/// <summary>Gets or sets UserLevel</summary>
        public Int32 UserLevel {
        	get { return m_userLevel; }
        	set { m_userLevel = value;}        
        }
		
	    #endregion
		
        #region Score

        private Int32 m_score;
		
		/// <summary>Gets or sets Score</summary>
        public Int32 Score {
        	get { return m_score; }
        	set { m_score = value;}        
        }
		
	    #endregion
		
        #region IsStop

        private Boolean m_isStop;
		
		/// <summary>Gets or sets IsStop</summary>
        public Boolean IsStop {
        	get { return m_isStop; }
        	set { m_isStop = value;}        
        }
		
	    #endregion
		
        #region CreateTime

        private DateTime m_createTime;
		
		/// <summary>Gets or sets CreateTime</summary>
        public DateTime CreateTime {
        	get { return m_createTime; }
        	set { m_createTime = value;}        
        }
		
	    #endregion
		
        #region UpdateTime

        private DateTime? m_updateTime;
		
		/// <summary>Gets or sets UpdateTime</summary>
        public DateTime? UpdateTime {
        	get { return m_updateTime; }
        	set { m_updateTime = value;}        
        }
		
	    #endregion
        /// <summary>
        /// 冻结金额
        /// </summary>
        public decimal FrozenAmount { get; set; }
        /// <summary>
        ///  累积兑换金额
        /// </summary>
        public decimal TotalExchange { get; set; }

        public U_UserInfo User { get; set; }
	}
	
}
