//==============================================================================
//	CAUTION: This file is generated by IBatisNetGen.Entity.cst at 2010-12-17 15:46:13
//				Any manual editing will be lost in re-generation.
//==============================================================================
using System;
using System.Collections.Generic;
using System.Text;

namespace TMM.Model {
	
    /// <summary><c>TJoinDoc</c> Business Object.</summary>
    [Serializable]
    public partial class TJoinDoc {
        
        #region JoinId

        private Int32 m_joinId;
		
		/// <summary>Gets or sets JoinId</summary>
        public Int32 JoinId {
        	get { return m_joinId; }
        	set { m_joinId = value;}        
        }
		
	    #endregion
		
        #region TId

        private Int32 m_tId;
		
		/// <summary>Gets or sets TId</summary>
        public Int32 TId {
        	get { return m_tId; }
        	set { m_tId = value;}        
        }
		
	    #endregion
		
        #region UserId

        private Int32 m_userId;
		
		/// <summary>Gets or sets UserId</summary>
        public Int32 UserId {
        	get { return m_userId; }
        	set { m_userId = value;}        
        }
		
	    #endregion
		
        #region Title

        private String m_title;
		
		/// <summary>Gets or sets Title</summary>
        public String Title {
        	get { return m_title; }
        	set { m_title = value;}        
        }
		
	    #endregion
		
        #region DocId

        private Int32 m_docId;
		
		/// <summary>Gets or sets DocId</summary>
        public Int32 DocId {
        	get { return m_docId; }
        	set { m_docId = value;}        
        }
		
	    #endregion
        /// <summary>
        /// 是否中标
        /// </summary>
        public bool IsWin { get; set; }

        public DateTime CreateTime { get; set; }
        /// <summary>
        /// 中标时间
        /// </summary>
        public DateTime? WinTime { get; set; }
        /// <summary>
        /// 关联的悬赏文档
        /// </summary>
        public TReqDoc ReqDoc { get; set; }
        /// <summary>
        /// 关联的投稿文档
        /// </summary>
        public DDocInfo DocInfo { get; set; }
	}
	
}
