//==============================================================================
//	CAUTION: This file is generated by IBatisNetGen.DaoImpl.cst at 2011-1-10 9:29:13
//				By xincai.wu
//==============================================================================
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using TMM.Model;
using TMM.Persistence;


namespace TMM.Service.Dal.Doc {

	/// <summary>
    /// 名称：MCatalogDao 数据层
    /// 开发者：
    /// 创建时间：2011-1-9 11:03:46
    /// 功能描述：
    /// </summary>
    public partial class MCatalogDal {

		/// <summary>
        /// 取得记录数
        /// </summary>
        /// <param name="param">可选参数为：</param>
        /// <returns></returns>
		public int GetCount(Hashtable param) {
			if (param == null)
                param = new Hashtable();
				
			String stmtId = "MCatalog.GetCount";
			return SqlMapper.Instance().QueryForObject<int>(stmtId, null);
		}

		/// <summary>
        /// 提取数据
        /// </summary>
        /// <param name="param">可选参数为：</param>
        /// <param name="orderBy">排序方式:默认为“CateId asc”</param>
        /// <param name="first">起始记录：从0开始</param>
        /// <param name="rows">提取的条数</param>
        /// <returns></returns>
		public IList<MCatalog> GetList(Hashtable param,string orderBy,int first,int rows) 
		{
			if (param == null)
                param = new Hashtable();

            param.Add("Top", first+ rows);
            param.Add("StartRecord", first);

            if (string.IsNullOrEmpty(orderBy))
                param.Add("OrderBy", "CateId asc");
			else
                param.Add("OrderBy", orderBy);
				
			String stmtId = "MCatalog.GetList";
			return SqlMapper.Instance().QueryForList<MCatalog>(stmtId, param);
		}
		
		/// <summary>
        /// 提取数据
        /// </summary>
        /// <param name="cateId"></param>
        /// <returns></returns>
		public MCatalog Get(Int32 cateId) {
			String stmtId = "MCatalog.Get";
			return SqlMapper.Instance().QueryForObject<MCatalog>(stmtId, cateId);
		}

		/// <summary>
        /// 插入数据
        /// </summary>
        /// <param name="obj">对象</param>
        /// <returns>返回：该条数据的主键Id</returns>
		public int Insert(MCatalog obj) {
			if (obj == null) throw new ArgumentNullException("obj");
			String stmtId = "MCatalog.Insert";
			return SqlMapper.Instance().QueryForObject<int>(stmtId, obj);
		}
		
		/// <summary>
        /// 更新数据
        /// </summary>
        /// <param name="obj"></param>
        /// <returns>返回：ture 成功，false 失败</returns>
		public bool Update(MCatalog obj) {
			if (obj == null) throw new ArgumentNullException("obj");
			String stmtId = "MCatalog.Update";
			int result = SqlMapper.Instance().QueryForObject<int>(stmtId, obj);
			return result > 0 ? true : false;
		}
		
		/// <summary>
        /// 删除数据
        /// </summary>
        /// <param name="cateId"></param>
        /// <returns>返回：ture 成功，false 失败</returns>
		public bool Delete(Int32 cateId) {
			String stmtId = "MCatalog.Delete";
			int result = SqlMapper.Instance().QueryForObject<int>(stmtId, cateId);
			return result > 0 ? true : false;
		}
		
	}

}
