//==============================================================================
//	CAUTION: This file is generated by IBatisNetGen.BLL.cst at 2011-1-10 10:09:48
//				By xincai.wu
//==============================================================================
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using TMM.Model;

namespace TMM.Service.Bll.User {

	/// <summary>
    /// 名称：MPurchaseDao 逻辑层
    /// 创建者：
    /// 创建时间：2011-1-9 11:06:52
    /// 功能描述：
    /// </summary>
    public partial class MPurchaseBLL {

        Dal.User.MPurchaseDal dal = new Dal.User.MPurchaseDal();

		/// <summary>
        /// 取得记录数
        /// </summary>
        /// <param name="param">可选参数为：</param>
        /// <returns></returns>
		public int GetCount(Hashtable param) {
			return dal.GetCount(param);
		}

		/// <summary>
        /// 提取数据
        /// </summary>
        /// <param name="param">可选参数为：</param>
        /// <param name="orderBy">排序方式:默认为“Pid asc”</param>
        /// <param name="first">起始记录：从0开始</param>
        /// <param name="rows">提取的条数</param>
        /// <returns></returns>
		public IList<MPurchase> GetList(Hashtable param,string orderBy,int first,int rows) 
		{
			return dal.GetList(param, orderBy, first, rows);
		}

        public IList<MPurchase> GetList(int userId,int first,int rows,out int count) {
            Hashtable p = new Hashtable();
            p.Add("UserId",userId);
            count = GetCount(p);
            return GetList(p, null, first, rows);
        }
        public IList<MPurchase> GetList(int userId, int first, int rows)
        {
            Hashtable p = new Hashtable();
            p.Add("UserId", userId);
            return GetList(p, null, first, rows);
        }
		
		/// <summary>
        /// 提取数据
        /// </summary>
        /// <param name="pid"></param>
        /// <returns></returns>
		public MPurchase Get(Int32 pid) {
			return dal.Get(pid);
		}

		/// <summary>
        /// 插入数据
        /// </summary>
        /// <param name="obj">对象</param>
        /// <returns>返回：该条数据的主键Id</returns>
		public int Insert(MPurchase obj) {
			return dal.Insert(obj);
		}
		
		/// <summary>
        /// 更新数据
        /// </summary>
        /// <param name="obj"></param>
        /// <returns>返回：ture 成功，false 失败</returns>
		public bool Update(MPurchase obj) {
			return dal.Update(obj);
		}
		
		/// <summary>
        /// 删除数据
        /// </summary>
        /// <param name="pid"></param>
        /// <returns>返回：ture 成功，false 失败</returns>
		public bool Delete(Int32 pid) {
			return dal.Delete(pid);
		}
        /// <summary>
        /// 是否已经购买过某个文档
        /// </summary>
        /// <param name="userId"></param>
        /// <param name="docId"></param>
        /// <returns></returns>
        public bool IsPurchase(int userId, int docId) { 
            Hashtable p = new Hashtable();
            p.Add("UserId",userId);
            p.Add("DocId",docId);
            IList<MPurchase> list = GetList(p, null, 0, 1);
            if (list == null)
                return false;
            else
                return list.Count > 0;
        }
	}

}
