//==============================================================================
//	CAUTION: This file is generated by IBatisNetGen.DaoImpl.cst at 2011-1-10 9:29:13
//				By xincai.wu
//==============================================================================
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using TMM.Model;
using TMM.Persistence;


namespace TMM.Service.Dal.User {

	/// <summary>
    /// 名称：MPurchaseDao 数据层
    /// 开发者：
    /// 创建时间：2011-1-9 11:03:46
    /// 功能描述：
    /// </summary>
    public partial class MPurchaseDal {

		/// <summary>
        /// 取得记录数
        /// </summary>
        /// <param name="param">可选参数为：</param>
        /// <returns></returns>
		public int GetCount(Hashtable param) {
			if (param == null)
                param = new Hashtable();
				
			String stmtId = "MPurchase.GetCount";
			return SqlMapper.Instance().QueryForObject<int>(stmtId, param);
		}

		/// <summary>
        /// 提取数据
        /// </summary>
        /// <param name="param">可选参数为：</param>
        /// <param name="orderBy">排序方式:默认为“Pid asc”</param>
        /// <param name="first">起始记录：从0开始</param>
        /// <param name="rows">提取的条数</param>
        /// <returns></returns>
		public IList<MPurchase> GetList(Hashtable param,string orderBy,int first,int rows) 
		{
			if (param == null)
                param = new Hashtable();

            param.Add("Top", first+ rows);
            param.Add("StartRecord", first);

            if (string.IsNullOrEmpty(orderBy))
                param.Add("OrderBy", "Pid desc");
			else
                param.Add("OrderBy", orderBy);
				
			String stmtId = "MPurchase.GetList";
			return SqlMapper.Instance().QueryForList<MPurchase>(stmtId, param);
		}
		
		/// <summary>
        /// 提取数据
        /// </summary>
        /// <param name="pid"></param>
        /// <returns></returns>
		public MPurchase Get(Int32 pid) {
			String stmtId = "MPurchase.Get";
			return SqlMapper.Instance().QueryForObject<MPurchase>(stmtId, pid);
		}

		/// <summary>
        /// 插入数据
        /// </summary>
        /// <param name="obj">对象</param>
        /// <returns>返回：该条数据的主键Id</returns>
		public int Insert(MPurchase obj) {
			if (obj == null) throw new ArgumentNullException("obj");
			String stmtId = "MPurchase.Insert";
			return SqlMapper.Instance().QueryForObject<int>(stmtId, obj);
		}
		
		/// <summary>
        /// 更新数据
        /// </summary>
        /// <param name="obj"></param>
        /// <returns>返回：ture 成功，false 失败</returns>
		public bool Update(MPurchase obj) {
			if (obj == null) throw new ArgumentNullException("obj");
			String stmtId = "MPurchase.Update";
			int result = SqlMapper.Instance().QueryForObject<int>(stmtId, obj);
			return result > 0 ? true : false;
		}
		
		/// <summary>
        /// 删除数据
        /// </summary>
        /// <param name="pid"></param>
        /// <returns>返回：ture 成功，false 失败</returns>
		public bool Delete(Int32 pid) {
			String stmtId = "MPurchase.Delete";
			int result = SqlMapper.Instance().QueryForObject<int>(stmtId, pid);
			return result > 0 ? true : false;
		}
		
	}

}
