//==============================================================================
//	CAUTION: This file is generated by IBatisNetGen.DaoImpl.cst at 2010-11-29 15:51:35
//				By xincai.wu
//==============================================================================
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using TMM.Model;
using TMM.Persistence;


namespace TMM.Service.Dal.User {

	/// <summary>
    /// 名称：UUserInfoDao 数据层
    /// 开发者：
    /// 创建时间：2010-11-29 19:03:15
    /// 功能描述：
    /// </summary>
    public partial class U_UserInfoDal {

		/// <summary>
        /// 取得记录数
        /// </summary>
        /// <param name="param">可选参数为：</param>
        /// <returns></returns>
		public int GetCount(Hashtable param) {
			if (param == null)
                param = new Hashtable();
				
			String stmtId = "U_UserInfo.GetCount";
			return SqlMapper.Instance().QueryForObject<int>(stmtId, param);
		}

		/// <summary>
        /// 提取数据
        /// </summary>
        /// <param name="param">可选参数为：</param>
        /// <param name="orderBy">排序方式:默认为“UserId asc”</param>
        /// <param name="first">起始记录：从0开始</param>
        /// <param name="rows">提取的条数</param>
        /// <returns></returns>
		public IList<U_UserInfo> GetList(Hashtable param,string orderBy,int first,int rows) 
		{
			if (param == null)
                param = new Hashtable();

            param.Add("Top", first+ rows);
            param.Add("StartRecord", first);

            if (string.IsNullOrEmpty(orderBy))
                param.Add("OrderBy", "UserId asc");
			else
                param.Add("OrderBy", orderBy);
				
			String stmtId = "U_UserInfo.GetList";
			return SqlMapper.Instance().QueryForList<U_UserInfo>(stmtId, param);
		}
		
		/// <summary>
        /// 提取数据
        /// </summary>
        /// <param name="userId"></param>
        /// <returns></returns>
		public U_UserInfo Get(Int32 userId) {
			String stmtId = "U_UserInfo.Get";
			return SqlMapper.Instance().QueryForObject<U_UserInfo>(stmtId, userId);
		}

		/// <summary>
        /// 插入数据
        /// </summary>
        /// <param name="obj">对象</param>
        /// <returns>返回：该条数据的主键Id</returns>
		public int Insert(U_UserInfo obj) {
			if (obj == null) throw new ArgumentNullException("obj");
			String stmtId = "U_UserInfo.Insert";
			return SqlMapper.Instance().QueryForObject<int>(stmtId, obj);
		}
		
		/// <summary>
        /// 更新数据
        /// </summary>
        /// <param name="obj"></param>
        /// <returns>返回：ture 成功，false 失败</returns>
		public bool Update(U_UserInfo obj) {
			if (obj == null) throw new ArgumentNullException("obj");
			String stmtId = "U_UserInfo.Update";
			int result = SqlMapper.Instance().QueryForObject<int>(stmtId, obj);
			return result > 0 ? true : false;
		}
        /// <summary>
        /// 更新马甲状态
        /// </summary>
        /// <param name="userId"></param>
        /// <param name="isMj"></param>
        /// <returns></returns>
        public bool UpdateMj(int userId, bool isMj)
        {
            String stmtId = "U_UserInfo.UpdateMj";
            Hashtable p = new Hashtable();
            p.Add("UserId",userId);
            p.Add("IsMajia",isMj);
            int result = SqlMapper.Instance().QueryForObject<int>(stmtId, p);
            return result > 0 ? true : false;
        }
		
		/// <summary>
        /// 删除数据
        /// </summary>
        /// <param name="userId"></param>
        /// <returns>返回：ture 成功，false 失败</returns>
		public bool Delete(Int32 userId) {
			String stmtId = "U_UserInfo.Delete";
			int result = SqlMapper.Instance().QueryForObject<int>(stmtId, userId);
			return result > 0 ? true : false;
		}
        /// <summary>
        /// 更新用户的上传文档数量
        /// </summary>
        /// <param name="uploadCount"></param>
        public void UpdateUploadCount(int uploadCount,int userId)
        {
            String stmtId = "U_UserInfo.UpdateUploadCount";
            Hashtable p = new Hashtable();
            p.Add("UploadCount",uploadCount);
            p.Add("UserId",userId);
            int result = SqlMapper.Instance().QueryForObject<int>(stmtId, p);
          
        }
		
	}

}
