//==============================================================================
//	CAUTION: This file is generated by IBatisNetGen.BLL.cst at 2010-11-29 15:51:35
//				By xincai.wu
//==============================================================================
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using TMM.Model;

namespace TMM.Service.Bll.Doc {

	/// <summary>
    /// 名称：DCommentDao 逻辑层
    /// 创建者：
    /// 创建时间：2010-11-29 19:12:38
    /// 功能描述：
    /// </summary>
    public partial class D_CommentBLL {

	Dal.Doc.D_CommentDal dal = new Dal.Doc.D_CommentDal();

		/// <summary>
        /// 取得记录数
        /// </summary>
        /// <param name="param">可选参数为：</param>
        /// <returns></returns>
		public int GetCount(Hashtable param) {
			return dal.GetCount(param);
		}

		/// <summary>
        /// 提取数据
        /// </summary>
        /// <param name="param">可选参数为：</param>
        /// <param name="orderBy">排序方式:默认为“CommentId asc”</param>
        /// <param name="first">起始记录：从0开始</param>
        /// <param name="rows">提取的条数</param>
        /// <returns></returns>
		public IList<D_Comment> GetList(Hashtable param,string orderBy,int first,int rows) 
		{
			return dal.GetList(param, orderBy, first, rows);
		}
		
		/// <summary>
        /// 提取数据
        /// </summary>
        /// <param name="commentId"></param>
        /// <returns></returns>
		public D_Comment Get(Int32 commentId) {
			return dal.Get(commentId);
		}

		/// <summary>
        /// 插入数据
        /// </summary>
        /// <param name="obj">对象</param>
        /// <returns>返回：该条数据的主键Id</returns>
		public int Insert(D_Comment obj) {
			return dal.Insert(obj);
		}
		
		/// <summary>
        /// 更新数据
        /// </summary>
        /// <param name="obj"></param>
        /// <returns>返回：ture 成功，false 失败</returns>
		public bool Update(D_Comment obj) {
			return dal.Update(obj);
		}
		
		/// <summary>
        /// 删除数据
        /// </summary>
        /// <param name="commentId"></param>
        /// <returns>返回：ture 成功，false 失败</returns>
		public bool Delete(Int32 commentId) {
			return dal.Delete(commentId);
		}
        /// <summary>
        /// 返回某文档的评论列表，只取最新100条
        /// </summary>
        /// <param name="docId"></param>
        /// <returns></returns>
        public IList<D_Comment> GetList(int docId)
        {
            Hashtable p = new Hashtable();
            p.Add("DocId",docId);
            p.Add("IsDisp",true);
            return GetList(p, null, 0, 100);
        }
        public IList<D_Comment> GetListForAdmin(int docId)
        {
            Hashtable p = new Hashtable();
            p.Add("DocId", docId);
            return GetList(p, null, 0, 9999999);
        }
        public int GetCount(int docId)
        {
            Hashtable p = new Hashtable();
            p.Add("DocId", docId);
            return GetCount(p);
        }
	}

}
