//==============================================================================
//	CAUTION: This file is generated by IBatisNetGen.BLL.cst at 2010-12-17 15:46:12
//				By xincai.wu
//==============================================================================
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using TMM.Model;

namespace TMM.Service.Bll.Admin {

	/// <summary>
    /// 名称：ManageUserDao 逻辑层
    /// 创建者：
    /// 创建时间：2010-11-29 19:12:38
    /// 功能描述：
    /// </summary>
    public partial class ManageUserBLL {

        Dal.Admin.ManageUserDal dal = new TMM.Service.Dal.Admin.ManageUserDal();

		/// <summary>
        /// 取得记录数
        /// </summary>
        /// <param name="param">可选参数为：</param>
        /// <returns></returns>
		public int GetCount(Hashtable param) {
			return dal.GetCount(param);
		}

		/// <summary>
        /// 提取数据
        /// </summary>
        /// <param name="param">可选参数为：</param>
        /// <param name="orderBy">排序方式:默认为“UserName asc”</param>
        /// <param name="first">起始记录：从0开始</param>
        /// <param name="rows">提取的条数</param>
        /// <returns></returns>
		public IList<ManageUser> GetList(Hashtable param,string orderBy,int first,int rows) 
		{
			return dal.GetList(param, orderBy, first, rows);
		}

        public bool IsExist(string userName, string password) {
            Hashtable p = new Hashtable();
            p.Add("UserName", userName);
            p.Add("Password", password);
            return GetList(p, null, 0, 1).Count > 0;
        }
		
		/// <summary>
        /// 提取数据
        /// </summary>
        /// <param name="userName"></param>
        /// <returns></returns>
		public ManageUser Get(String userName) {
			return dal.Get(userName);
		}

		/// <summary>
        /// 插入数据
        /// </summary>
        /// <param name="obj">对象</param>
        /// <returns>返回：该条数据的主键Id</returns>
		public int Insert(ManageUser obj) {
			return dal.Insert(obj);
		}
		
		/// <summary>
        /// 更新数据
        /// </summary>
        /// <param name="obj"></param>
        /// <returns>返回：ture 成功，false 失败</returns>
		public bool Update(ManageUser obj) {
			return dal.Update(obj);
		}
		
		/// <summary>
        /// 删除数据
        /// </summary>
        /// <param name="userName"></param>
        /// <returns>返回：ture 成功，false 失败</returns>
		public bool Delete(String userName) {
			return dal.Delete(userName);
		}
		
	}

}
