//==============================================================================
//	CAUTION: This file is generated by IBatisNetGen.BLL.cst at 2010-12-17 22:06:24
//				By xincai.wu
//==============================================================================
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using TMM.Model;

namespace TMM.Service.Bll.Order
{

	/// <summary>
    /// 名称：TOrderDetailDao 逻辑层
    /// 创建者：
    /// 创建时间：2011-1-9 11:06:52
    /// 功能描述：
    /// </summary>
    public partial class TOrderDetailBLL {

        Dal.Order.TOrderDetailDal dal = new Dal.Order.TOrderDetailDal();

		/// <summary>
        /// 取得记录数
        /// </summary>
        /// <param name="param">可选参数为：</param>
        /// <returns></returns>
		public int GetCount(Hashtable param) {
			return dal.GetCount(param);
		}

		/// <summary>
        /// 提取数据
        /// </summary>
        /// <param name="param">可选参数为：</param>
        /// <param name="orderBy">排序方式:默认为“OrderDetailId asc”</param>
        /// <param name="first">起始记录：从0开始</param>
        /// <param name="rows">提取的条数</param>
        /// <returns></returns>
		public IList<TOrderDetail> GetList(Hashtable param,string orderBy,int first,int rows) 
		{
			return dal.GetList(param, orderBy, first, rows);
		}
        public IList<TOrderDetail> GetList(decimal orderId) {
            Hashtable p = new Hashtable();
            p.Add("OrderId",orderId);
            return GetList(p, null, 0, 1);
        }
		
		/// <summary>
        /// 提取数据
        /// </summary>
        /// <param name="orderDetailId"></param>
        /// <returns></returns>
		public TOrderDetail Get(Int32 orderDetailId) {
			return dal.Get(orderDetailId);
		}

		/// <summary>
        /// 插入数据
        /// </summary>
        /// <param name="obj">对象</param>
        /// <returns>返回：该条数据的主键Id</returns>
		public int Insert(TOrderDetail obj) {
			return dal.Insert(obj);
		}
		
		/// <summary>
        /// 更新数据
        /// </summary>
        /// <param name="obj"></param>
        /// <returns>返回：ture 成功，false 失败</returns>
		public bool Update(TOrderDetail obj) {
			return dal.Update(obj);
		}
		
		/// <summary>
        /// 删除数据
        /// </summary>
        /// <param name="orderDetailId"></param>
        /// <returns>返回：ture 成功，false 失败</returns>
		public bool Delete(Int32 orderDetailId) {
			return dal.Delete(orderDetailId);
		}
		
	}

}
